### PR TITLE
Update TextLinkListView

### PR DESCRIPTION
**Pull request by onmyway133**
- Subclass from UIView instead of UITableViewCell
- Also, in `Item+Extensions`, import UIKit in order for CGFloat to work, if not we will get this

float

This should break Mac target for now

### CODE REVIEW

**Review by zenangst — APPROVED** [review]
👍

**Comment by onmyway133** [comment]
@zenangst we use `CGFloat` so it should import `UIKit`, not sure about Mac target

**Comment by zenangst** [comment]
@onmyway133 You could add a preprocessor, not the prettiest solution but it would do the job.

```swift
#if os(macOS)
  import Cocoa
#else
  import UIKit
#endif
```

**Comment by zenangst** [comment]
@onmyway133 feel free to merge this :)

**Pull request merged**
